 # @package _global_
config:
  MULTI_PROCESSING_METHOD: forkserver 
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      SHOULD_FLATTEN_FEATS: False
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
          ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
    HEAD:
      PARAMS: [
          ["mlp", {"dims": [2048, 1000]}],
      ]
    WEIGHTS_INIT:
      PARAMS_FILE: "split_model.pth"
  DATA:
    NUM_DATALOADER_WORKERS: 1
    TRAIN:
      DATA_SOURCES: [disk_folder]
      DATA_PATHS: ["imagenet1k/ILSVRC/Data/CLS-LOC/train"]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
    TEST:
      DATA_SOURCES: [disk_folder]
      DATA_PATHS: ["imagenet1k/ILSVRC/Data/CLS-LOC/train"]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
